### ISSUE TITLE
wav encoding

### ISSUE THREAD

**Issue by arran4** [zalgonoise/x#13]
What is the status of the repo?

**Comment by zalgonoise** [comment]
Hi @arran4, thanks :) This repository is exclusively experimental so in here you could expect sudden breaking changes. I will be sure to follow up with `x/audio` as soon as it's done by porting it to its own repo.

To answer your question:
- as a library it's working fine for PCM audio. I haven't started with FPA yet. Most likely PCM should cover most requirements, already.
- its dependencies like `gbuf` are fully tested and working.
- the spectrum analysis package is working (you can work with peaks and spectrum)
- the latest binary implementation (in `cmd/audio`) currently supports monitoring (peaks) and analysis (spectrum), or both. Recording, recording on event, and exposing a (HTTP) audio source in the future.

I hope this helps. If you have any questions on its usage in the meantime feel free to bump this issue again. I will be happy to chip in while it's experimental.

**Comment by arran4** [comment]
Thanks I've been meaning to play around with audio so I just want to try it out. I have noted it, not sure when I will get time though. But thanks for answering so promptly.

**Comment by zalgonoise** [comment]
No problem. My use case was audio via an HTTP stream, so other solutions using io.ReadSeeker weren't cutting it. :)

I hope it is useful to you, too.
